### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by chenmeiya** [meijianhan/DeepDeblur#1]
Hi. @meijianhan The code is used for any paper? Or not?

**Comment by meijianhan** [comment]
Hi. Actually, yes, we submit a paper with this code. Once the paper is accepted, we will provide the citation in the readme. Please feel free to use the code, and announce our work, thanks.

**Comment by chenmeiya** [comment]
Is the paper presented in arixv? Thanks for your answer.

**Comment by meijianhan** [comment]
Sorry, we do not put it to arxiv yet, but we may plan to do that later.

**Comment by chenmeiya** [comment]
Ok, thank you.
