### ISSUE TITLE
Training patch dimension

### ISSUE THREAD

**Issue by VikasRajashekar** [meijianhan/DeepDeblur#3]
is it necessary to have 65X65X3? I ran your MTABLAB function on my images and the dimension was 65X65. I was able to train the model. But when I test I face the following issue:
ValueError: Layer #1 (named "model_1"), weight <tf.Variable 'conv2d_19/kernel:0' shape=(3, 3, 128, 1) dtype=float32_ref> has shape (3, 3, 128, 1), but the saved weight has shape (128, 128, 3, 3).

**Comment by meijianhan** [comment]
It is not necessary to use the patch dimension of (65, 65). We use such dimension just for the balance of the memory usage and the image scale.

I am not quite sure about your problem. It looks like the model weight shape mismatch while loading.

Our default code is using the patch dimension of (65, 65, 1). And in your case, you are using the (65, 65, 3). So maybe you forgot to change the "num_of_dim = 3" while training?

**Comment by VikasRajashekar** [comment]
@meijianhan Thanks for the clarification. I'm sorry, I trained it with patches of size 65X65 too. I am trying to load the model in test.py with the final h5 file created at the end of the training(ModelFinal.h5).
I see that you are printing the summary. 
I observed that  DeblurNet.summary() [line no:40 test.py] has conv2d_19 as the last layer. And this is exactly in sync with your saved weights(DeblurSHC19ConvLayers.hdf5) But when I had a look at the saved file after training (ModelFinal.h5) it has extra layers conv2d_20 and conv2d_21and also i observed few extra optimizer weights in ModelFinal.h5. I belive this is the reason for not able to load. Why is it happening? I exactly followed your instructions

**Comment by meijianhan** [comment]
Yes, the model used in training and testing needs to keep consistent. So please use the exact same function to build the model. ( DeblurNet = ShortCutNet().DeblurSHCNet(input_dim, 15) ).

I am sorry that we put different settings in the default training and testing code.

**Comment by VikasRajashekar** [comment]
ah. Thanks for the clarification. It works.
I have one more doubt. Can this network be used to train different dimension images? 
instead of 65*65 patch. I would like to train with bigger patches. or the whole image itself.

**Comment by meijianhan** [comment]
Yes, this work can be used for any dimension of image training.

**Comment by VikasRajashekar** [comment]
Thanks closing the issue.
