### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by Zepharchit** [meijianhan/DeepDeblur#4]
Hi, I am trying to train the model with my own data, I have images of varying dimensions when I am trying to run it this error is popping up

PATH
path_sharp = '/home/jediyoda/archit/Dat_Noh/train/train_h/'
path_blur = '/home/jediyoda/archit/Dat_Noh/train/train_l/'
Params
batch_size = 128
epochs = 21
input image dimensions
img_rows = 65
img_cols = 65
num_of_dim = 3

Using the following parameters to try training the model.

![Screenshot from 2020-09-25 15-14-46](https://user-images.githubusercontent.com/51807559/94252831-18f73500-ff42-11ea-85c1-ecee93ef440c.png)

**Comment by simonchanper** [comment]
Hi,

thank you for your e-mail.

Judging from your screenshot, your input shape is incorrect. E.g. array of size 65*65*3 = 12675, and you are inputting array of size 880075 should be likely (64.433925, 65, 65, 3). In addition, 880075 is not divisible by 12675, so you need to check whether your input shape is correct.

Thank you very much!

Best,
Simon

**Comment by Zepharchit** [comment]
A query like for training should I have the dataset with images being of the same dimension?

**Comment by meijianhan** [comment]
Yes, training images of the same dimension are required.

**Comment by Zepharchit** [comment]
Thanks.
